a = (input('Digite algo: '))

print('O tipo primitivo é ', type(a))
print(f'Oque você digitou é numerico?  ', {a.isnumeric()})
print(f'Oque você digitou é alfabetico? ', {a.isalpha()})
print(f'Oque voce digitou é alfanumerico?' ,{a.isalnum()})
print(f'Todos os caracteres estão em maiusculo?', {a.isupper()})
print(f'Todos os caracteres estao em minusculo?', {a.islower()})
print(f'Está capitalizado?', {a.istitle()})
print(f'Só tem espaços?', {a.isspace()})